### PR TITLE
Make text easier to read

### PR DESCRIPTION
**Pull request by douglashill**
This is somewhat jokey, but that super light text is really hard on the eyes. Maybe more of a discussion point than something I’d expect you to merge.

I didn’t test building the site because I could not find any instructions.

### CODE REVIEW

**Comment by jakepetroules** [comment]
gem install jekyll && jekyll build

Sorry, this should be made clearer.

**Comment by jakepetroules** [comment]
Not sure if I like it... maybe if we do normal for body but keep the navigation bar at 200? @pornel, thoughts?

**Comment by douglashill** [comment]
Visually this change isn’t great as it messes with the balance of the design.

My thought process was:

- Light text is hard to read (on my non-retina screen).
- So make text bolder with User CSS.
- Since it’s just for me, my goal is readability rather than overall aesthetics.
- Hmm, this site is on GitHub, so why not share this change and at least start a discussion.

**Comment by pornel** [comment]
It is easier to read. It's clearly much better choice for documentation pages.

With bolder text we'll also need to make headers bolder or otherwise stand out more.

The thin font does look neat though. Maybe we could keep it just on the home page? Maybe just for `@media (min-resolution:2dppx)`? or use darker color than `#666`?

**Comment by jakepetroules** [comment]
I think if we simply use `.navbar { font-weight: 200; }` instead of `body { font-weight: 200; }` it will look pretty decent and we can merge it. Thoughts?

**Comment by pornel** [comment]
:+1:

**Comment by douglashill** [comment]
I agree leaving the navbar alone is better. I’ve force pushed my branch to do that.

**Pull request merged**
