### PR TITLE
Redesign the Sparkle website with a more modern look and feel.

### PR DESCRIPTION
**Pull request by jakepetroules**
The website now shows the version number of the current Sparkle release!

Also, it's mobile friendly.

### CODE REVIEW

**Comment by jakepetroules** [comment]
It's been a long time coming, but I finally found the time to do it. Hopefully everyone agrees this is a huge improvement over the current site; I think it will improve Sparkle's branding a lot. Of course, design feedback is welcomed and encouraged!

I was also working on a new "flat design" logo to match the modern design of the new website and OS X itself. I'm not much of a graphic designer so I can't really decide if this looks good or not. Might be best to let someone else take up this task.

sparkle-logo

To check out the new site, cd to the repo root and run: `sudo gem install jekyll && jekyll serve && open 'http://localhost:4000'`

**Comment by jakepetroules** [comment]
Here's a few screenshots for convenience or if you don't want to install Jekyll.

screen shot 2015-07-23 at 2 52 51 pm
screen shot 2015-07-23 at 2 53 15 pm
screen shot 2015-07-23 at 2 53 19 pm
screen shot 2015-07-23 at 2 53 24 pm

**Comment by pornel** [comment]
Thank you very much. A website refresh was very needed!

It has a bit of a bare-boostrap feel, but I think we can add tweaks later (sadly, I'm not a designer either :)

**Comment by zorgiepoo** [comment]
Looks neat! May want to have the 'Documentation' link just go directly to the GitHub page rather than going to a page that does a redirect.

**Comment by jakepetroules** [comment]
I was wondering if it might provide a better experience to provide Sparkle's documentation on the actual website instead of GitHub Wiki...

More control over design, better permalinks...

**Comment by pornel** [comment]
Maybe we can do both and somehow sync wiki and the website?

**Comment by jakepetroules** [comment]
Theoretically the website's CI could make commits but it's probably not worth the hassle to sync.

**Comment by zorgiepoo** [comment]
It may be advantageous for people to be able to edit/contribute to the documentation at any rate. One option is allowing people to make pull requests to the website repo if they want to make doc changes, and so that they can be reviewed? This is if we don't want to use GH wiki.

One thing I noticed: I'm not a huge fan of a nav bar that stays fixed when scrolling down the webpage. It is kind of big / space consuming too, at least on my mobile device. I presume this behavior is from bootstrap.

**Comment by jakepetroules** [comment]
> One option is allowing people to make pull requests to the website repo if they want to make doc changes, and so that they can be reviewed?

Exactly. Wiki is either entirely unmoderated, or editable only by those with push access. The website repo helps us meet in the middle using pull requests.

> One thing I noticed: I'm not a huge fan of a nav bar that stays fixed when scrolling down the webpage. It is kind of big / space consuming too, at least on my mobile device.

Hmm, I think you are right about that. It would make it consistent with the other pages where the navbar is not fixed (and good point about that being a bigger problem on mobile, especially since it's a particularly tall nav).

**Comment by zorgiepoo** [comment]
It's better now that the nav bar isn't fixed, but I still think it's too tall on Desktop. You can tell from the selection shadow/border. Bonus points if the download button is completely visible on my 11" MBA without scrolling.

**Comment by zorgiepoo** [comment]
[Image with max dock size](https://zgcoder.net/zfw/images/2015-07-24-21-40-52-EDT-493323.png).

**Comment by jakepetroules** [comment]
@zorgiepoo Main part of site should be visible on an 11" MBA now.

**Comment by zorgiepoo** [comment]
+1 it is. The selection shadow on the active tab might still be too tall on desktop however (lots of padded space).

**Comment by jakepetroules** [comment]
Feel free to experiment with it and send a PR if you think you find something that looks better. :)

**Pull request merged**
